### ISSUE TITLE
does not work on multisite

### ISSUE THREAD

**Issue by cfoellmann** [thomasgriffin/tgm-plugin-update-modal#1]
I did this a few weeks ago but I ran into the same issue you have with this example.
Due to crossorigin issues it is not possible to use this on a multisite. It is not a problem with your code but with core + current browsers.
Any idea on what needs to be done to solve this without modifying configs on the webserver side?

**Comment by thomasgriffin** [comment]
Unfortunately I do not have a solution for this. I've not been able to figure this one out either, other than using so really complicated code to try and intelligently guess where they are coming from and show different views if cross origin will be a problem.
